### ISSUE TITLE
NameError: name 'maxTime' is not defined

### ISSUE THREAD

**Issue by peoplecure** [joeljose/Visual-Mic#1]
Hey, can you explain why this error is showing up? I am using the KitKat.avi

```
python3 visualmic.py
201 1280 720
Video Loaded
Transform complete
Traceback (most recent call last):
  File "visualmic.py", line 106, in <module>
    main()
  File "visualmic.py", line 102, in main
    npTowav(soundfromvid(input_data,frameCount,nlevels,orient,ref_no,ref_orient,ref_level), "sound.wav")
  File "visualmic.py", line 52, in soundfromvid
    shift_matrix[i,j]=maxTime(ref_vector,data[:,i,j].reshape(-1))
NameError: name 'maxTime' is not defined
```

**Comment by joeljose** [comment]
Looks like I have uploaded the python file which had an error.
Because maxTime function is missing. I will reupload the correct code, in a week or so(Busy with another work).

**Comment by joeljose** [comment]
My code is not implemented for parallel processing. Sorry about that (So you might need high CPU to execute code on the original data, I did it on High RAM CPU )

**Comment by sjane-x** [comment]
> Looks like I have uploaded the python file which had an error.
> Because maxTime function is missing. I will reupload the correct code, in a week or so(Busy with another work).

hey, will you still be able to upload an updated version of you code? thank you

**Comment by V1lu0** [comment]
NameError: name 'maxTime' is not defined I'm also running into this issue, can you update the code

**Comment by joshterrill** [comment]
@peoplecure @sjane-x @V1lu0 I have forked this repo and have been fixing issues with the missing functions and broken documentation. I also made it easier to process video files by taking the video path in via command line arg instead of it being hard-coded. I'll be posting these updates between today and tomorrow if I can figure out a way to get the sample videos provided in the README working. Code works fine, runs all the way through, but the output wav doesn't appear to have sound in it. Also when I download the example AVI files from the README link, those don't appear to have audio in them either? I'm not sure if it's a me issue/codec issue, or I'm misunderstanding something. Hoping to have it resolved along with my changes pushed to the fork soon. I'll propose a PR once I'm done.

**Comment by joeljose** [comment]
I'm really sorry for the huge delay. I have updated the code. 
PS: The code is from when i had zero experience coding. I am planning on writing proper documentation, proper error handling etc. The code is also not optimised. I am planning on writing in c++ and cuda. Please do test the update given in the latest commit. I will close the issue once someone confirms.

**Comment by joeljose** [comment]
> @peoplecure @sjane-x @V1lu0 I have forked this repo and have been fixing issues with the missing functions and broken documentation. I also made it easier to process video files by taking the video path in via command line arg instead of it being hard-coded. I'll be posting these updates between today and tomorrow if I can figure out a way to get the sample videos provided in the README working. Code works fine, runs all the way through, but the output wav doesn't appear to have sound in it. Also when I download the example AVI files from the README link, those don't appear to have audio in them either? I'm not sure if it's a me issue/codec issue, or I'm misunderstanding something. Hoping to have it resolved along with my changes pushed to the fork soon. I'll propose a PR once I'm done.

The original paper on Visual mic has the video which is to be used. https://data.csail.mit.edu/vidmag/VisualMic/ videos are about 12GB.

**Comment by joeljose** [comment]
Added the missing functions, cross checked if it is working.
